// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf0w6Mi_XyzQPH3F4hWj4PAFOpH5D7RzM',
    appId: '1:440497001135:web:34d14940e36bc7bb7bba5a',
    messagingSenderId: '440497001135',
    projectId: 'tiketinnusa',
    authDomain: 'tiketinnusa.firebaseapp.com',
    storageBucket: 'tiketinnusa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAmos6NFv1HoBFQQD87S95zKb9We0brqQ',
    appId: '1:440497001135:android:66246617f5c1a3a27bba5a',
    messagingSenderId: '440497001135',
    projectId: 'tiketinnusa',
    storageBucket: 'tiketinnusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8wNY_hrg9QyJ2HKLJla6_3xdtKkxijWA',
    appId: '1:440497001135:ios:122c198dd08dd56c7bba5a',
    messagingSenderId: '440497001135',
    projectId: 'tiketinnusa',
    storageBucket: 'tiketinnusa.firebasestorage.app',
    iosBundleId: 'com.example.tiketinnusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8wNY_hrg9QyJ2HKLJla6_3xdtKkxijWA',
    appId: '1:440497001135:ios:122c198dd08dd56c7bba5a',
    messagingSenderId: '440497001135',
    projectId: 'tiketinnusa',
    storageBucket: 'tiketinnusa.firebasestorage.app',
    iosBundleId: 'com.example.tiketinnusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf0w6Mi_XyzQPH3F4hWj4PAFOpH5D7RzM',
    appId: '1:440497001135:web:3696017b864cba977bba5a',
    messagingSenderId: '440497001135',
    projectId: 'tiketinnusa',
    authDomain: 'tiketinnusa.firebaseapp.com',
    storageBucket: 'tiketinnusa.firebasestorage.app',
  );
}
